In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\Sagar\Downloads\customer.csv")

In [3]:
df.sample(5)

age  gender   review education purchased
37   94    Male  Average        PG       Yes
2    70  Female     Good        PG        No
4    16  Female  Average        UG        No
40   39    Male     Good    School        No
22   18  Female     Poor        PG       Yes

In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [9]:
X_train

review education
28     Poor    School
39     Poor        PG
13  Average    School
41     Good        PG
0   Average    School
4   Average        UG
32  Average        UG
7      Poor    School
46     Poor        PG
1      Poor        UG
22     Poor        PG
47     Good        PG
3      Good        PG
37  Average        PG
23     Good    School
18     Good    School
15     Poor        UG
5   Average    School
33     Good        PG
8   Average        UG
45     Poor        PG
30  Average        UG
43     Poor        PG
2      Good        PG
29  Average        UG
38     Good    School
36     Good        UG
25     Good    School
14     Poor        PG
10     Good        UG
35     Poor    School
27     Poor        PG
11     Good        UG
21  Average        PG
40     Good    School
20  Average    School
34  Average    School
9      Good        UG
16     Poor        UG
44  Average        UG

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
X_train

review education
28     Poor    School
39     Poor        PG
13  Average    School
41     Good        PG
0   Average    School
4   Average        UG
32  Average        UG
7      Poor    School
46     Poor        PG
1      Poor        UG
22     Poor        PG
47     Good        PG
3      Good        PG
37  Average        PG
23     Good    School
18     Good    School
15     Poor        UG
5   Average    School
33     Good        PG
8   Average        UG
45     Poor        PG
30  Average        UG
43     Poor        PG
2      Good        PG
29  Average        UG
38     Good    School
36     Good        UG
25     Good    School
14     Poor        PG
10     Good        UG
35     Poor    School
27     Poor        PG
11     Good        UG
21  Average        PG
40     Good    School
20  Average    School
34  Average    School
9      Good        UG
16     Poor        UG
44  Average        UG

In [22]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [23]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [31]:
X_train

array([[0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [1., 1.]])

In [32]:

oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [33]:
X_train

array([[0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [1., 1.]])

In [34]:
from sklearn.preprocessing import LabelEncoder


In [36]:
le = LabelEncoder()

In [37]:
le.fit(y_train)

LabelEncoder()

In [38]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [39]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [40]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0])